CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR,
    created      timestamp WITHOUT TIME ZONE             not null,
    requestor_id BIGINT                                  NOT NUlL
        CONSTRAINT fk_requests_user_id REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS fk_requests_index ON requests (requestor_id);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(1500),
    is_available BOOLEAN,
    owner_id     BIGINT                                  NOT NULL
        CONSTRAINT fk_items_user_id REFERENCES users (id) ON DELETE CASCADE,
    request_id   BIGINT
        CONSTRAINT fk_items_request_id REFERENCES requests (id),
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS fk_items_users_index ON items (owner_id);
CREATE INDEX IF NOT EXISTS fk_items_requests_index ON items (request_id);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    status     varchar(255),
    item_id    BIGINT                                  NOT NULL
        CONSTRAINT fk_bookings_item_id REFERENCES items (id),
    booker_id  BIGINT                                  NOT NULL
        CONSTRAINT fk_bookings_user_id REFERENCES users (id),
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS fk_bookings_items_index ON bookings (item_id);
CREATE INDEX IF NOT EXISTS fk_bookings_users_index ON bookings (booker_id);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      VARCHAR                                 NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item_id   BIGINT                                  NOT NULL REFERENCES items (id),
    author_id BIGINT                                  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS fk_comments_items_index ON comments (item_id);
CREATE INDEX IF NOT EXISTS fk_comments_users_index ON comments (author_id);